export const rawTwitterResponse = [
  {
    created_at: "Tue Feb 18 21:46:10 +0000 2020",
    id: 1229884838687182800,
    id_str: "1229884838687182848",
    text:
      "@chunkyguy @nicklockwood @peres In any case assoc. object is great — it enables magic in many libraries incl.… https://t.co/l2mJYbFuuG",
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Array],
      urls: [Array]
    },
    metadata: { iso_language_code: "en", result_type: "recent" },
    source:
      '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 1229883558895984600,
    in_reply_to_status_id_str: "1229883558895984640",
    in_reply_to_user_id: 1121459347,
    in_reply_to_user_id_str: "1121459347",
    in_reply_to_screen_name: "_andersha",
    user: {
      id: 1121459347,
      id_str: "1121459347",
      name: "Anders Ha",
      screen_name: "_andersha",
      location: "London, United Kingdom",
      description: "Software Engineer. Does iOS.",
      url: null,
      entities: [Object],
      protected: false,
      followers_count: 233,
      friends_count: 114,
      listed_count: 8,
      created_at: "Sat Jan 26 09:16:53 +0000 2013",
      favourites_count: 198,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 478,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "9AE4E8",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme16/bg.gif",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme16/bg.gif",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1180711762154414081/yju5ZKSe_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1180711762154414081/yju5ZKSe_normal.jpg",
      profile_link_color: "0084B4",
      profile_sidebar_border_color: "BDDCAD",
      profile_sidebar_fill_color: "DDFFCC",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none"
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: "en"
  },
  {
    created_at: "Tue Feb 18 03:49:34 +0000 2020",
    id: 1229613903417684000,
    id_str: "1229613903417683969",
    text:
      "@pourhadi Take UIKit, RxSwift/ReactiveCocoa, SnapKit. Avoid Interface Builder. Add new Xcode Canvas. You are as pro… https://t.co/n8JFhbaJOD",
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Array],
      urls: [Array]
    },
    metadata: { iso_language_code: "en", result_type: "recent" },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: 1229613352076431400,
    in_reply_to_status_id_str: "1229613352076431361",
    in_reply_to_user_id: 1215979394,
    in_reply_to_user_id_str: "1215979394",
    in_reply_to_screen_name: "a_grebenyuk",
    user: {
      id: 1215979394,
      id_str: "1215979394",
      name: "Alexander Grebenyuk",
      screen_name: "a_grebenyuk",
      location: "New York, NY",
      description:
        "Software Engineer • Writing https://t.co/Nz30g2Hv1Y • Open Source https://t.co/OYUtDgr8Nb • Authored Nuke, Future, Align, Arranged, Regex and more",
      url: "https://t.co/pWRxRqAZIj",
      entities: [Object],
      protected: false,
      followers_count: 932,
      friends_count: 160,
      listed_count: 42,
      created_at: "Sun Feb 24 16:46:34 +0000 2013",
      favourites_count: 3524,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1399,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "000000",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/729537146919501824/PcO6kt6A_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/729537146919501824/PcO6kt6A_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/1215979394/1576200259",
      profile_link_color: "1A25FB",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "000000",
      profile_text_color: "000000",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none"
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en"
  }
];
